### ISSUE TITLE
Upgrade peerDependencies for React 0.14

### ISSUE THREAD

**Issue by tlvenn** [JedWatson/react-container#3]
Hi,

With React 0.14 being released now, it would be great to update this library so it can play well with it.

Thanks

**Comment by JedWatson** [comment]
Done! Published `0.3.0` with `react@0.14` dependency.

**Comment by tlvenn** [comment]
Thanks @JedWatson !

Any chance React-Tappable can receive the same treatment ? ;)

**Comment by JedWatson** [comment]
@Tlvenn sure thing :)
