### ISSUE TITLE
What does initScrollable do?

### ISSUE THREAD

**Issue by pke** [JedWatson/react-container#4]
and what is it used for?

**Comment by jossmac** [comment]
It's used to maintain the scroll-position of a container when you navigate away and then back to it, used like:

``` jsx
const Container = require('react-container');
const scrollable = Container.initScrollable();

<Container scrollable={scrollable} />
```

https://github.com/Thinkmill/reacteu-app has some good examples

**Comment by pke** [comment]
Ah thanks!
