### ISSUE TITLE
Consider inline styles?

### ISSUE THREAD

**Issue by pke** [JedWatson/react-container#5]
Have you considered using inline styles?
This would make the component easier to integrate into css-less react apps.

**Comment by jossmac** [comment]
@pke yeah that would be awesome. We're planning to refactor [Elemental](https://github.com/elementalui/elemental) to use [React JSS](https://github.com/jsstyles/react-jss). Would you be confident submitting a PR for this?

**Comment by pke** [comment]
I am not sure. I am not that confident with react-container yet. I need to take a closer look at the current CSS.
For instance I wonder what for the ´#react-container` selector is used. Should it even be part of the component? It certainly cannot be part of the inline styled component.

**Comment by jossmac** [comment]
Okay @pke let me know where you get up to :)

**Comment by pke** [comment]
Created my own container from scratch.
